apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dp
  namespace: app
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: otus-hw
        image: kali7va/otus-hw:0.3
        ports:
        - containerPort: 8000
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: server.port
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: url
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-postgresql
              key: password
